spring.application.name=user-service
server.port=4001
access.token=${ACCESS_TOKEN}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.security=DEBUG
    