spring.application.name=course-service
server.port=4002
aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.region=${AWS_DEFAULT_REGION}
aws.bucketName=${AWS_BUCKET_NAME}
#aws.bucket.name=${AWS_BUCKET_NAME}
#4002