services:
  enrollment-service:
    build:
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://enrollmentDB:5432/${POSTGRES_DB}?sslmode=disable
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${PORT}
    depends_on:
      - enrollmentDB
    networks:
      - education-service

  enrollmentDB:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - enrollment-db:/var/lib/postgresql/data
    networks:
      - education-service

volumes:
  enrollment-db:

networks:
  education-service: